# Generated by Django 5.0.2 on 2024-02-15 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roomreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomreview',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
