# Generated by Django 5.0.2 on 2024-02-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_roomreview_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreview',
            old_name='blog',
            new_name='room',
        ),
    ]
