# Generated by Django 5.0.2 on 2024-02-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_rename_blog_roomreview_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomimages',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
