# Generated by Django 5.0.2 on 2024-02-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_bookroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
