# Generated by Django 5.0.2 on 2024-02-19 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_room_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRoom',
        ),
        migrations.AlterField(
            model_name='roomcontent',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_room', to='room.room'),
        ),
        migrations.AlterField(
            model_name='roomimages',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room.room'),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_review_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roomreview',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_room', to='room.room'),
        ),
    ]
