# Generated by Django 5.0.2 on 2024-02-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_delete_bookroom_alter_roomcontent_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
